# Generated by Django 6.0.7 on 2026-07-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matric_number',
            field=models.CharField(blank=True, help_text='e.g. 2021/241832CS', max_length=20),
        ),
    ]
