# Generated by Django 6.0.7 on 2026-07-15 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_reservation_completed_at_reservation_qr_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='completed_at',
            new_name='picked_up_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('picked_up', 'Picked Up'), ('returned', 'Returned')], default='pending', max_length=10),
        ),
    ]
